In [1]:
from pathlib import Path
import yaml

In [2]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
import seaborn as sns

In [3]:
import yfinance as yf

## load multi index finance data

In [4]:
def load_stock_data(ticker, start_date, end_date):
    try:
        return yf.download(ticker, start=start_date, end=end_date)
    except Exception as e:
        print(f"Error loading stock data: {e}")
        return None

## convert the multi-index data to single index data

In [5]:
def load_multi_index_finance_data(tickers, start_date, end_date):
    try:
        data = yf.download(tickers=tickers, start=start_date, end=end_date)

        # drop ticker level and keep only date level
        # data.index = data.index.droplevel('Ticker')
        data.columns = data.columns.droplevel(1)

        #reset the date index into column
        data.reset_index(inplace=True)

        return data
    except Exception as e:
        print(f"Error loading data: {e}")
        return None

In [6]:
data = load_multi_index_finance_data('AAPL', '2020-01-01', '2020-12-31')
data

[*********************100%***********************]  1 of 1 completed

Price       Date       Close        High         Low        Open     Volume
0     2020-01-02   72.468269   72.528589   71.223267   71.476607  135480400
1     2020-01-03   71.763718   72.523746   71.539330   71.696160  146322800
2     2020-01-06   72.335556   72.374162   70.634539   70.885472  118387200
3     2020-01-07   71.995346   72.600952   71.775781   72.345197  108872000
4     2020-01-08   73.153503   73.455103   71.698589   71.698589  132079200
..           ...         ...         ...         ...         ...        ...
247   2020-12-23  127.483330  128.914291  127.308101  128.651470   88223700
248   2020-12-24  128.466492  129.916941  127.619593  127.833754   54930100
249   2020-12-28  133.061172  133.693910  129.965587  130.432855  124486200
250   2020-12-29  131.289520  135.105452  130.773592  134.385107  121047300
251   2020-12-30  130.170029  132.379769  129.858517  131.980650   96452100

[252 rows x 6 columns]

In [7]:
data.columns

Index(['Date', 'Close', 'High', 'Low', 'Open', 'Volume'], dtype='object', name='Price')

## remove price and convert proper time series

In [8]:
def load_stock_data(tickers, start_date, end_date):
    try:
        data = yf.download(
            tickers=tickers, 
            start=start_date, 
            end=end_date, 
            group_by='column'
        )

        # drop ticker level (i.e. 0 , "AAPL")
        if isinstance(data.columns, pd.MultiIndex):
            data.columns = data.columns.droplevel(1)

        # remove column index name ("Price")
        data.columns.name = None

        # ensure proper time-series format
        data.index.name = 'date'
        data.sort_index(inplace=True)

        return data
        
    except Exception as e:
        print(f"Error loading stock data: {e}")
        return None

In [9]:
ticker = 'AAPL'
start_date = '2015-01-01'
end_date = '2023-12-31'
data = load_stock_data(ticker, start_date, end_date)
data

[*********************100%***********************]  1 of 1 completed

                 Close        High         Low        Open     Volume
date
2015-01-02   24.237551   24.705320   23.798600   24.694235  212818400
2015-01-05   23.554743   24.086803   23.368523   24.006994  257142000
2015-01-06   23.556955   23.816334   23.195597   23.619029  263188400
2015-01-07   23.887285   23.987046   23.654508   23.765354  160423600
2015-01-08   24.805086   24.862726   24.097889   24.215387  237458000
...                ...         ...         ...         ...        ...
2023-12-22  191.788773  193.581837  191.164662  193.353978   37149600
2023-12-26  191.243912  192.076049  191.025969  191.798670   28919300
2023-12-27  191.342972  191.689703  189.302247  190.689158   48087700
2023-12-28  191.768936  192.838834  191.362768  192.323695   34049900
2023-12-29  190.728775  192.581275  189.936256  192.085953   42672100

[2264 rows x 5 columns]

In [10]:
import yfinance as yf
import pandas as pd

def load_multi_index_finance_data(tickers, start_date, end_date):
    try:
        data = yf.download(
            tickers=tickers,
            start=start_date,
            end=end_date,
            group_by="column"
        )

        # Drop ticker level (AAPL, MSFT, etc.)
        if isinstance(data.columns, pd.MultiIndex):
            data.columns = data.columns.droplevel(1)

        # Remove column index name ("Price")
        data.columns.name = None

        # Ensure proper time-series format
        data.index.name = "date"
        data = data.sort_index()

        return data

    except Exception as e:
        print(f"Error loading data: {e}")
        return None


data = load_multi_index_finance_data("AAPL", "2015-01-01", "2023-12-31")
data

[*********************100%***********************]  1 of 1 completed

                 Close        High         Low        Open     Volume
date
2015-01-02   24.237551   24.705320   23.798600   24.694235  212818400
2015-01-05   23.554743   24.086803   23.368523   24.006994  257142000
2015-01-06   23.556955   23.816334   23.195597   23.619029  263188400
2015-01-07   23.887285   23.987046   23.654508   23.765354  160423600
2015-01-08   24.805086   24.862726   24.097889   24.215387  237458000
...                ...         ...         ...         ...        ...
2023-12-22  191.788773  193.581837  191.164662  193.353978   37149600
2023-12-26  191.243912  192.076049  191.025969  191.798670   28919300
2023-12-27  191.342972  191.689703  189.302247  190.689158   48087700
2023-12-28  191.768936  192.838834  191.362768  192.323695   34049900
2023-12-29  190.728775  192.581275  189.936256  192.085953   42672100

[2264 rows x 5 columns]

In [11]:
data = load_multi_index_finance_data("AAPL", "2015-01-01", "2023-12-31")
data

[*********************100%***********************]  1 of 1 completed

                 Close        High         Low        Open     Volume
date
2015-01-02   24.237551   24.705320   23.798600   24.694235  212818400
2015-01-05   23.554743   24.086803   23.368523   24.006994  257142000
2015-01-06   23.556955   23.816334   23.195597   23.619029  263188400
2015-01-07   23.887285   23.987046   23.654508   23.765354  160423600
2015-01-08   24.805086   24.862726   24.097889   24.215387  237458000
...                ...         ...         ...         ...        ...
2023-12-22  191.788773  193.581837  191.164662  193.353978   37149600
2023-12-26  191.243912  192.076049  191.025969  191.798670   28919300
2023-12-27  191.342972  191.689703  189.302247  190.689158   48087700
2023-12-28  191.768936  192.838834  191.362768  192.323695   34049900
2023-12-29  190.728775  192.581275  189.936256  192.085953   42672100

[2264 rows x 5 columns]

In [12]:
import yfinance as yf
import pandas as pd

def load_finance_ts(
    ticker: str,
    start_date: str,
    end_date: str,
) -> pd.DataFrame | None:
    try:
        # ---- Clean inputs ----
        ticker = ticker.strip().upper()
        start_date = str(start_date).strip()
        end_date = str(end_date).strip()

        # ---- Download ----
        data = yf.download(
            tickers=ticker,
            start=start_date,
            end=end_date,
            auto_adjust=False,
            progress=False,
        )

        # ---- Guard: empty download ----
        if data.empty:
            raise ValueError("No data returned. Check ticker or date range.")

        # ---- Handle MultiIndex columns ----
        if isinstance(data.columns, pd.MultiIndex):
            data.columns = data.columns.droplevel(1)

        # ---- Remove column index name (e.g. 'Price') ----
        data.columns.name = None

        # ---- Time series formatting ----
        data.index.name = "date"
        data = data.sort_index()

        return data

    except Exception as e:
        print(f"Error loading finance data: {e}")
        return None

In [13]:
data = load_multi_index_finance_data("AAPL", "2015-01-01", "2023-12-31")
data

[*********************100%***********************]  1 of 1 completed

                 Close        High         Low        Open     Volume
date
2015-01-02   24.237551   24.705320   23.798600   24.694235  212818400
2015-01-05   23.554743   24.086803   23.368523   24.006994  257142000
2015-01-06   23.556955   23.816334   23.195597   23.619029  263188400
2015-01-07   23.887285   23.987046   23.654508   23.765354  160423600
2015-01-08   24.805086   24.862726   24.097889   24.215387  237458000
...                ...         ...         ...         ...        ...
2023-12-22  191.788773  193.581837  191.164662  193.353978   37149600
2023-12-26  191.243912  192.076049  191.025969  191.798670   28919300
2023-12-27  191.342972  191.689703  189.302247  190.689158   48087700
2023-12-28  191.768936  192.838834  191.362768  192.323695   34049900
2023-12-29  190.728775  192.581275  189.936256  192.085953   42672100

[2264 rows x 5 columns]

In [14]:
data.columns

Index(['Close', 'High', 'Low', 'Open', 'Volume'], dtype='object')

In [15]:
df.index

NameError: name 'df' is not defined

---
---

In [ ]:
def load_stock_data(ticker, start_date, end_date):
    try:
        return yf.download(ticker, start=start_date, end=end_date)
    except Exception as e:
        print(f"Error loading stock data: {e}")
        return None

In [16]:
data = load_stock_data("AAPL", "2015-01-01", "2023-12-31")
data

[*********************100%***********************]  1 of 1 completed

                 Close        High         Low        Open     Volume
date
2015-01-02   24.237551   24.705320   23.798600   24.694235  212818400
2015-01-05   23.554743   24.086803   23.368523   24.006994  257142000
2015-01-06   23.556955   23.816334   23.195597   23.619029  263188400
2015-01-07   23.887285   23.987046   23.654508   23.765354  160423600
2015-01-08   24.805086   24.862726   24.097889   24.215387  237458000
...                ...         ...         ...         ...        ...
2023-12-22  191.788773  193.581837  191.164662  193.353978   37149600
2023-12-26  191.243912  192.076049  191.025969  191.798670   28919300
2023-12-27  191.342972  191.689703  189.302247  190.689158   48087700
2023-12-28  191.768936  192.838834  191.362768  192.323695   34049900
2023-12-29  190.728775  192.581275  189.936256  192.085953   42672100

[2264 rows x 5 columns]

In [17]:
data.columns

Index(['Close', 'High', 'Low', 'Open', 'Volume'], dtype='object')

In [18]:
data.index

DatetimeIndex(['2015-01-02', '2015-01-05', '2015-01-06', '2015-01-07',
               '2015-01-08', '2015-01-09', '2015-01-12', '2015-01-13',
               '2015-01-14', '2015-01-15',
               ...
               '2023-12-15', '2023-12-18', '2023-12-19', '2023-12-20',
               '2023-12-21', '2023-12-22', '2023-12-26', '2023-12-27',
               '2023-12-28', '2023-12-29'],
              dtype='datetime64[ns]', name='date', length=2264, freq=None)

In [19]:
data.head()

                Close       High        Low       Open     Volume
date
2015-01-02  24.237551  24.705320  23.798600  24.694235  212818400
2015-01-05  23.554743  24.086803  23.368523  24.006994  257142000
2015-01-06  23.556955  23.816334  23.195597  23.619029  263188400
2015-01-07  23.887285  23.987046  23.654508  23.765354  160423600
2015-01-08  24.805086  24.862726  24.097889  24.215387  237458000

In [20]:
# move price level to columns
data = data.pivot(index='Date', columns='Price', values='Value')
data

KeyError: 'Date'

In [ ]:
import pandas as pd

data = {'Date': ['2022-01-01', '2022-01-01', '2022-01-02', '2022-01-02'],
        'Price': ['Open', 'Close', 'Open', 'Close'],
        'Value': [100, 120, 110, 130]}

df = pd.DataFrame(data)

pivoted_df = df.pivot(index='Date', columns='Price', values='Value')
print(pivoted_df)

Price       Close  Open
Date
2022-01-01    120   100
2022-01-02    130   110

In [ ]:
df

         Date  Price  Value
0  2022-01-01   Open    100
1  2022-01-01  Close    120
2  2022-01-02   Open    110
3  2022-01-02  Close    130

In [ ]:
pivoted_df

Price       Close  Open
Date
2022-01-01    120   100
2022-01-02    130   110

In [ ]:
import pandas as pd
import yfinance as yf


def load_finance_time_series(
    ticker: str,
    start_date: str,
    end_date: str,
) -> pd.DataFrame:
    """
    Load financial time-series data and normalize it into a clean,
    forecasting-ready DataFrame.

    Returns:
        DataFrame indexed by date with columns:
        ['Open', 'High', 'Low', 'Close', 'Volume', 'Adj Close' (optional)]
    """

    # --------------------------------------------------
    # 1️⃣ Sanitize inputs (VERY IMPORTANT)
    # --------------------------------------------------
    ticker = ticker.strip().upper()
    start_date = str(start_date).strip()
    end_date = str(end_date).strip()

    # --------------------------------------------------
    # 2️⃣ Download data
    # --------------------------------------------------
    data = yf.download(
        tickers=ticker,
        start=start_date,
        end=end_date,
        auto_adjust=False,   # explicit to avoid future warning
        progress=False,
    )

    if data.empty:
        raise ValueError("No data returned. Check ticker or date range.")

    # --------------------------------------------------
    # 3️⃣ FIX: MultiIndex on COLUMNS (ticker level)
    # --------------------------------------------------
    if isinstance(data.columns, pd.MultiIndex):
        # drop ticker level (AAPL)
        data.columns = data.columns.droplevel(1)

    # remove column index name like "Price"
    data.columns.name = None

    # --------------------------------------------------
    # 4️⃣ FIX: MultiIndex on INDEX (Date, Price)
    # --------------------------------------------------
    if isinstance(data.index, pd.MultiIndex):
        if "Price" in data.index.names:
            # unstack price into columns
            data = data.unstack(level="Price")
            data.columns = data.columns.droplevel(0)

    # --------------------------------------------------
    # 5️⃣ Final cleanup
    # --------------------------------------------------
    data.index = pd.to_datetime(data.index)
    data.index.name = "date"
    data = data.sort_index()

    return data

In [ ]:
def

In [21]:
df = load_finance_time_series(
    ticker="AAPL",
    start_date="2020-01-01",
    end_date="2021-01-01"
)

print(df.head())
print(df.index)
print(df.columns)

NameError: name 'load_finance_time_series' is not defined

In [22]:
def load_stock_data(ticker: str, start_date: str, end_date: str, ) -> pd.DataFrame:
    # sanitize the inputs
    ticker = ticker.strip().upper()
    # start_date = pd.to_datetime(str(start_date).strip()).strftime('%Y-%m-%d')
    # end_date = pd.to_datetime(str(end_date).strip()).strftime('%Y-%m-%d')
    start_date = str(start_date).strip()
    end_date = str(end_date).strip()    

    # download data
    data = yf.download(ticker, start=start_date, end=end_date, auto_adjust=True, progress=False)
    if data.empty:
        raise ValueError(f"No data found for {stock} between {start_date} and {end_date}")
    
    # fix multi-index on column
    if isinstance(data.columns, pd.MultiIndex):
        # drop ticker level( 1, "AAPL")
        data.columns = data.columns.droplevel(1)
    
    # remove column index name (0, "Price")
    if isinstance(data.index, pd.MultiIndex):
        if "Price" in data.index.names:
            #unstack price into columns
            data = data.unstack(level="Price")
            data.columns = data.columns.droplevel(0)

    # final cleanup
    data.index = pd.to_datetime(data.index)
    data.index = 'date'
    data = data.sort_index()
    
    return data

In [23]:
df = load_stock_data(
    ticker="AAPL",
    start_date="2020-01-01",
    end_date="2021-01-01"
)
df

TypeError: Index(...) must be called with a collection of some kind, 'date' was passed

In [ ]:
import pandas as pd
import yfinance as yf


def load_finance_time_series(
    ticker: str,
    start_date: str,
    end_date: str,
) -> pd.DataFrame:
    """
    Load financial time-series data and normalize it into a clean,
    forecasting-ready DataFrame.

    Returns:
        DataFrame indexed by date with columns:
        ['Open', 'High', 'Low', 'Close', 'Volume', 'Adj Close' (optional)]
    """

    # sanitize inputs
    ticker = ticker.strip().upper()
    start_date = str(start_date).strip()
    end_date = str(end_date).strip()

    # download data
    data = yf.download(
        tickers=ticker,
        start=start_date,
        end=end_date,
        auto_adjust=False,   # explicit to avoid future warning
        progress=False,
    )

    if data.empty:
        raise ValueError("No data returned. Check ticker or date range.")


    # FIX: MultiIndex on column
    if isinstance(data.columns, pd.MultiIndex):
        # drop ticker level (AAPL)
        data.columns = data.columns.droplevel(1)

    # remove column index name like "Price"
    data.columns.name = None

    # FIX: MultiIndex on INDEX (Date, Price)
    if isinstance(data.index, pd.MultiIndex):
        if "Price" in data.index.names:
            # unstack price into columns
            data = data.unstack(level="Price")
            data.columns = data.columns.droplevel(0)

    # Final cleanup
    data.index = pd.to_datetime(data.index)
    data.index.name = "date"
    data = data.sort_index()

    return data

In [ ]:
df = load_finance_time_series(
    ticker="AAPL",
    start_date="2020-01-01",
    end_date="2021-01-01"
)

df

,Adj Close,Close,High,Low,Open,Volume
date,,,,,,
2020-01-02,72.468262,75.087502,75.150002,73.797501,74.059998,135480400
2020-01-03,71.763748,74.357498,75.144997,74.125000,74.287498,146322800
2020-01-06,72.335564,74.949997,74.989998,73.187500,73.447502,118387200
2020-01-07,71.995354,74.597504,75.224998,74.370003,74.959999,108872000
2020-01-08,73.153481,75.797501,76.110001,74.290001,74.290001,132079200
...,...,...,...,...,...,...
2020-12-24,128.466461,131.970001,133.460007,131.100006,131.320007,54930100
2020-12-28,133.061188,136.690002,137.339996,133.509995,133.990005,124486200
2020-12-29,131.289505,134.869995,138.789993,134.339996,138.050003,121047300
2020-12-30,130.169998,133.720001,135.990005,133.399994,135.580002,96452100
2020-12-31,129.167404,132.690002,134.740005,131.720001,134.080002,99116600